"""
PPT Generator Module - Premium Version
Creates high-end, professional PowerPoint presentations with AI-generated visuals.
"""
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.enum.shapes import MSO_SHAPE
import os
from datetime import datetime


class PPTGenerator:
    # Premium Color Palette
    DARK_BG = RGBColor(0x0A, 0x0A, 0x12)      # Very dark navy
    CARD_BG = RGBColor(0x15, 0x15, 0x25)      # Slightly lighter card color
    ACCENT_GREEN = RGBColor(0x00, 0xFF, 0x9D) # Neon battery green
    ACCENT_BLUE = RGBColor(0x00, 0xD1, 0xFF)  # Cyber blue
    WHITE = RGBColor(0xFF, 0xFF, 0xFF)
    TEXT_DIM = RGBColor(0xB0, 0xB0, 0xC0)     # Dimmed text
    SOURCE_HL = RGBColor(0xFF, 0xCC, 0x00)    # Source highlight gold

    SLIDE_COLORS = [ACCENT_GREEN, ACCENT_BLUE, RGBColor(0xFF, 0x7E, 0x5F), RGBColor(0xAD, 0x8E, 0xFF)]

    def __init__(self):
        self.prs = Presentation()
        # Set slide dimensions (widescreen 16:9)
        self.prs.slide_width = Inches(13.333)
        self.prs.slide_height = Inches(7.5)

    def _set_slide_bg(self, slide, color):
        """Set solid background color for a slide."""
        background = slide.background
        fill = background.fill
        fill.solid()
        fill.fore_color.rgb = color

    def _add_styled_text(self, shape, text, font_size=14, font_color=None, bold=False, alignment=PP_ALIGN.LEFT, font_name="맑은 고딕"):
        """Helper to style text inside a shape."""
        tf = shape.text_frame
        tf.word_wrap = True
        p = tf.paragraphs[0]
        p.text = text
        p.font.size = Pt(font_size)
        p.font.bold = bold
        p.font.name = font_name
        p.alignment = alignment
        if font_color:
            p.font.color.rgb = font_color
        return tf

    def _create_title_slide(self, title_text="2차전지 업계 동향 리포트", bg_image_path=None):
        """Create a stunning title slide with background image and overlay."""
        slide = self.prs.slides.add_slide(self.prs.slide_layouts[6])  # Blank
        
        if bg_image_path and os.path.exists(bg_image_path):
            # Insert background image to fill the slide
            slide.shapes.add_picture(bg_image_path, 0, 0, width=self.prs.slide_width, height=self.prs.slide_height)
            
            # Add semi-transparent dark overlay for text readability
            overlay = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, self.prs.slide_width, self.prs.slide_height)
            overlay.fill.solid()
            overlay.fill.fore_color.rgb = self.DARK_BG
            overlay.fill.transparency = 0.4  # 40% transparent
            overlay.line.fill.background()
        else:
            self._set_slide_bg(slide, self.DARK_BG)

        today = datetime.now().strftime("%Y. %m. %d")

        # Decorative neon line
        line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1), Inches(2.2), Inches(0.1), Inches(1.5))
        line.fill.solid()
        line.fill.fore_color.rgb = self.ACCENT_GREEN
        line.line.fill.background()

        # Main title
        title_box = slide.shapes.add_textbox(Inches(1.3), Inches(2.1), Inches(11), Inches(1.5))
        self._add_styled_text(title_box, title_text, font_size=48, font_color=self.WHITE, bold=True)

        # Subtitle
        sub_box = slide.shapes.add_textbox(Inches(1.3), Inches(3.4), Inches(11), Inches(0.8))
        self._add_styled_text(sub_box, "Weekly Battery Industry & Manufacturing Trend Analysis", 
                             font_size=18, font_color=self.ACCENT_BLUE, bold=True)

        # Info Box (Bottom Left)
        info_rect = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(1), Inches(6), Inches(4), Inches(0.8))
        info_rect.fill.solid()
        info_rect.fill.fore_color.rgb = self.CARD_BG
        info_rect.fill.transparency = 0.3
        info_rect.line.color.rgb = self.ACCENT_GREEN
        info_rect.line.width = Pt(1.5)
        
        self._add_styled_text(info_rect, f"Reported on: {today}\nGenerated by Antigravity AI", 
                             font_size=12, font_color=self.TEXT_DIM, alignment=PP_ALIGN.CENTER)

    def _create_content_slide(self, slide_info, slide_index=0):
        """Create a premium content slide with card-based layout."""
        slide = self.prs.slides.add_slide(self.prs.slide_layouts[6])
        self._set_slide_bg(slide, self.DARK_BG)

        accent_color = self.SLIDE_COLORS[slide_index % len(self.SLIDE_COLORS)]
        title = slide_info.get('title', 'Untitled Analysis')
        content_lines = slide_info.get('content', [])

        # 1. Header Area
        header_rect = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, self.prs.slide_width, Inches(0.8))
        header_rect.fill.solid()
        header_rect.fill.fore_color.rgb = self.CARD_BG
        header_rect.line.fill.background()
        
        # Issue Badge
        badge = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.5), Inches(0.2), Inches(1.2), Inches(0.4))
        badge.fill.solid()
        badge.fill.fore_color.rgb = accent_color
        badge.line.fill.background()
        self._add_styled_text(badge, f"ISSUE {slide_index + 1:02}", font_size=12, font_color=self.DARK_BG, bold=True, alignment=PP_ALIGN.CENTER)

        # Title
        title_box = slide.shapes.add_textbox(Inches(2), Inches(0.15), Inches(10), Inches(0.5))
        self._add_styled_text(title_box, title, font_size=24, font_color=self.WHITE, bold=True)

        # 2. Main Content Card
        card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(0.5), Inches(1.2), Inches(8.5), Inches(5.5))
        card.fill.solid()
        card.fill.fore_color.rgb = self.CARD_BG
        card.line.color.rgb = RGBColor(0x30, 0x30, 0x45)
        card.line.width = Pt(1)

        # Content Bullets
        text_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.5), Inches(7.9), Inches(5))
        tf = text_box.text_frame
        tf.word_wrap = True
        
        y_cursor = 0
        for line in content_lines:
            line = line.strip()
            if not line or line.startswith("📎") or "http" in line: continue
            
            p = tf.add_paragraph() if y_cursor > 0 else tf.paragraphs[0]
            p.text = "  ▶  " + line
            p.font.size = Pt(16)
            p.font.color.rgb = self.WHITE
            p.font.name = "맑은 고딕"
            p.space_after = Pt(12)
            y_cursor += 1

        # 3. Source / Insight Side Card
        side_card = slide.shapes.add_shape(MSO_SHAPE.ROUNDED_RECTANGLE, Inches(9.3), Inches(1.2), Inches(3.5), Inches(5.5))
        side_card.fill.solid()
        side_card.fill.fore_color.rgb = RGBColor(0x10, 0x10, 0x20)
        side_card.line.color.rgb = accent_color
        side_card.line.width = Pt(1.5)

        side_title = slide.shapes.add_textbox(Inches(9.5), Inches(1.4), Inches(3), Inches(0.4))
        self._add_styled_text(side_title, "SOURCES & LINKS", font_size=14, font_color=accent_color, bold=True)

        # Extract URLs
        urls = [l.strip() for l in content_lines if "http" in l]
        url_box = slide.shapes.add_textbox(Inches(9.5), Inches(2.0), Inches(3.1), Inches(4.5))
        utf = url_box.text_frame
        utf.word_wrap = True
        
        for i, url in enumerate(urls[:6]):
            p = utf.add_paragraph() if i > 0 else utf.paragraphs[0]
            clean_url = url.replace("📎 출처:", "").replace("  ", "").strip()
            p.text = f"Link {i+1}: {clean_url[:40]}..." if len(clean_url) > 40 else clean_url
            p.font.size = Pt(10)
            p.font.color.rgb = self.ACCENT_BLUE
            p.font.underline = True
            p.space_after = Pt(8)

        # Bottom Page Number
        self._add_textbox(slide, 12, 7, 1, 0.3, str(slide_index + 2), font_size=10, font_color=self.TEXT_DIM, alignment=PP_ALIGN.RIGHT)

    def _add_textbox(self, slide, left, top, width, height, text, font_size=14, font_color=None, bold=False, alignment=PP_ALIGN.LEFT):
        """Standard textbox helper for backward compatibility/extra info."""
        txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
        self._add_styled_text(txBox, text, font_size, font_color, bold, alignment)
        return txBox.text_frame

    def _create_summary_slide(self):
        """Create a high-impact closing slide."""
        slide = self.prs.slides.add_slide(self.prs.slide_layouts[6])
        self._set_slide_bg(slide, self.DARK_BG)

        # Center Graphic
        circle = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(5.1), Inches(1.5), Inches(3), Inches(3))
        circle.fill.solid()
        circle.fill.fore_color.rgb = self.CARD_BG
        circle.line.color.rgb = self.ACCENT_GREEN
        circle.line.width = Pt(3)
        
        self._add_textbox(slide, 5.1, 2.5, 3, 1, "⚡", font_size=60, font_color=self.ACCENT_GREEN, alignment=PP_ALIGN.CENTER)

        self._add_textbox(slide, 2, 4.8, 9, 1, "End of Report", font_size=32, font_color=self.WHITE, bold=True, alignment=PP_ALIGN.CENTER)
        self._add_textbox(slide, 2, 5.6, 9, 0.5, "본 보고서는 AI 자동화 시스템에 의해 생성되었습니다.", font_size=14, font_color=self.TEXT_DIM, alignment=PP_ALIGN.CENTER)

    def create_presentation(self, slides_data, output_file="battery_trend_report.pptx", bg_image_path=None):
        """Creates a premium PPT presentation."""
        # Title slide
        self._create_title_slide(bg_image_path=bg_image_path)

        # Content slides
        for i, slide_info in enumerate(slides_data):
            self._create_content_slide(slide_info, i)

        # Summary slide
        self._create_summary_slide()

        # Save
        self.prs.save(output_file)
        print(f"[PPT Generator] Premium presentation saved to {output_file}")
        return os.path.abspath(output_file)


if __name__ == "__main__":
    gen = PPTGenerator()
    data = [
        {
            'title': '전고체 배터리 양산 경쟁 가속화',
            'content': [
                '삼성SDI, 2026년 전고체 배터리 파일럿 라인 가동 시작',
                '토요타, 2027년 전고체 배터리 탑재 EV 출시 계획 발표',
                '에너지 밀도 500Wh/kg 이상으로 기존 리튬이온 대비 2배',
                '주요 과제: 대량생산 비용 절감 및 계면 저항 문제 해결',
                '시장 규모 2030년까지 150억 달러 전망',
                '',
                '📎 출처:',
                'https://example.com/solid-state'
            ]
        },
        {
            'title': '나트륨이온 배터리 상용화 진전',
            'content': [
                'CATL, 나트륨이온 2세대 셀 양산 개시',
                'kWh당 40달러 이하 원가 달성으로 가격 혁신',
                'ESS 및 저가형 EV 시장에서 LFP 대체 가능성',
                '리튬 의존도 감소로 공급망 안정성 확보',
                '한계: 에너지 밀도 160Wh/kg 수준',
            ]
        },
    ]
    gen.create_presentation(data, "test_professional.pptx")
    print("Test PPT generated!")
