from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
import os

class PPTGenerator:
    def __init__(self):
        self.prs = Presentation()

    def create_presentation(self, slides_data, output_file="battery_trend_report.pptx"):
        """
        Creates a PPT presentation from a list of slide data.
        slides_data: list of dicts -> [{'title': 'Slide Title', 'content': ['Bullet 1', 'Bullet 2']}]
        """
        # 1. Title Slide
        title_slide_layout = self.prs.slide_layouts[0]
        slide = self.prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        title.text = "Battery Trend Report"
        subtitle.text = "Latest Issues & Trends\nGenerated by AI Reporter"

        # 2. Content Slides
        bullet_slide_layout = self.prs.slide_layouts[1] # Title and Content

        for slide_info in slides_data:
            slide = self.prs.slides.add_slide(bullet_slide_layout)
            shapes = slide.shapes
            
            title_shape = shapes.title
            title_shape.text = slide_info.get('title', 'No Title')

            body_shape = shapes.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True

            content_lines = slide_info.get('content', [])
            if isinstance(content_lines, str):
                 content_lines = [content_lines]
            
            # Clear existing paragraphs (if any)
            # tf.clear() # Not strictly necessary for new slides

            for i, line in enumerate(content_lines):
                if i == 0:
                    p = tf.text_frame.paragraphs[0] if hasattr(tf, 'text_frame') else tf.paragraphs[0]
                    p.text = line
                else:
                    p = tf.add_paragraph()
                    p.text = line
                
                p.font.size = Pt(14)
                # p.level = 0 # Default

        # Save
        self.prs.save(output_file)
        print(f"[PPT Generator] Saved presentation to {output_file}")
        return os.path.abspath(output_file)

if __name__ == "__main__":
    # Test
    gen = PPTGenerator()
    data = [
        {'title': 'Issue 1: Sodium Ion Batteries', 'content': ['Cheaper than Lithium', 'Abundant resources', 'Lower energy density but improving']},
        {'title': 'Issue 2: Solid State Batteries', 'content': ['Safety improved', 'High cost barrier broken', 'Mass production checks']}
    ]
    gen.create_presentation(data)
